language: cpp
sudo: required

install:
  - curl http://ubuntu.openturns.org/openturns.org-repo.key | sudo apt-key add -
  - echo deb http://ubuntu.openturns.org precise main | sudo tee /etc/apt/sources.list.d/openturns.list
  - sudo apt-get update
#- sudo apt-get -y install libopenturns-dev python-openturns cmake gfortran swig texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python-sphinx python-matplotlib dvipng
  - sudo apt-get -y install cmake gfortran swig texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python-sphinx python-matplotlib dvipng libxml2-dev liblapack-dev libmuparser-dev libboost-math-dev libtbb-dev libnlopt-dev libhmat-oss-dev python-dev
# use master for now
  - git clone https://github.com/openturns/openturns.git
  - wget --no-check-certificate https://github.com/openturns/openturns/pull/195.patch; patch -p1 -i 195.patch
  - pushd openturns
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DUSE_SPHINX=OFF .
  - make install -j2
  - popd

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local
    -DOpenTURNS_DIR=~/.local/lib/cmake/openturns
    .
  - make install -j2 && make tests -j2 && ctest -j2 --output-on-failure --timeout 100 

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" || exit 0
  - git clone https://${GH_TOKEN}@github.com/openturns/openturns.github.io.git
  - REPO_NAME=`echo "${TRAVIS_REPO_SLUG}" | cut -d "/" -f 2`
  - mkdir -p openturns.github.io/${REPO_NAME}/${TRAVIS_BRANCH}
  - cp -r ~/.local/share/${REPO_NAME}/doc/html/* openturns.github.io/${REPO_NAME}/${TRAVIS_BRANCH}
  - cd openturns.github.io
  - touch .nojekyll
  - git config user.email "support@travis-ci.com"
  - git config user.name "Travis CI"
  - git add -A .
  - git commit -a -m "Travis build ${REPO_NAME} ${TRAVIS_BUILD_NUMBER}"
  - git push --quiet origin master > /dev/null 2>&1

env:
  global:
    secure: kJXOGPSdgD5NUe0Egn2ohDTAl/1bXjgMBQBPYEexG0eUSVa1kjbamXJ8rCANteAFJS2LlS3A+oMLDd1GWOjaiZIOs8453ogyjKi5lbXdByNGZyzsig/oct65N/D/TFzF5iVRx3yd6+mUAx82vIVDtC3Cz6d9N3FHfjLaFvRhp4HGmAi9vh1sxOHoWGmh5XpaJJi+JNIou6kBSuwcTP6V/J0vLtQFFPf/zgpS3ZNHc9ZEzxzvRmNMZ7u3q0mofMz/pYrhFf1swcYoLlmyrmJjscrNOwXGnwOpsiR+srfCy5i0kHdips30f0iSWbkHpKPWuR51kChAIPYP2QSxeXQeVGTh5jOt35V6ygaVM8OvNX5ey5ncwihWsUSB72HoguCiIZ1A1Zt9UwL3yDizo9H0lZOnOTNIs2vPK4tEy2nMWLC7SBeGUpdW1dJBVztUierxIN34erQXWvCI5KPo65MlC/Crhr+PmzFGuua36fnheR/GMTedtuOJKWMBxHdsT2PkB2XtxTywmIn8rTp3R1R464jFacoEGCdYom+oqnEkuDhrQ4oC41vmvsEqCi2EtrIj/SimFgrlL2z9V5dWfheM9PSRYm69O3T6hoWdg0BYoWZYgfTO6DihZezet2KUeaNYIfZpGJdLIoJPK+PnVc4qLo5th9gjdvNMtrK02qxLN50=
